trigger:
- main

pool:
  vmImage: 'Windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/SpecFlowAzure'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'SpecFlowAzure/SpecFlowAzure.csproj'
    arguments: --configuration $(BuildConfiguration)
    workingDirectory: '$(System.DefaultWorkingDirectory)/SpecFlowAzure'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'SpecFlowAzure/SpecFlowAzure.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    zipAfterPublish: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/SpecFlowAzure'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'